-- Generated by scripts/cloudflare/generate_d1_baseline.py.
-- Schema generated from a freshly initialized main SQLite database.

PRAGMA foreign_keys = OFF;
CREATE TABLE fragments (
  id INTEGER PRIMARY KEY,
  date_rule TEXT,
  behaviour TEXT,
  propers TEXT
);
CREATE TABLE holidays (
  id INTEGER PRIMARY KEY,
  handle TEXT,
  date_rule TEXT,
  style TEXT,
  priority INTEGER,
  colour TEXT,
  propers TEXT,
  name TEXT,
  alternative_name TEXT,
  importable_fragments TEXT
);
CREATE TABLE pages (
  id INTEGER PRIMARY KEY,
  title TEXT,
  content TEXT,
  slug TEXT NOT NULL
);
CREATE TABLE pco_batch_sync_jobs (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  status TEXT NOT NULL,
  request_payload TEXT NOT NULL,
  results_json TEXT,
  summary_json TEXT,
  error TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  started_at TEXT,
  completed_at TEXT,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE pco_connections (
  user_id INTEGER PRIMARY KEY,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  token_type TEXT,
  scope TEXT,
  expires_at TEXT,
  pco_account_name TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE service_custom_elements (
  id INTEGER PRIMARY KEY,
  service_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE service_custom_templates (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE service_pco_item_links (
  id INTEGER PRIMARY KEY,
  service_id INTEGER NOT NULL,
  ordinarium_token TEXT NOT NULL,
  pco_item_id TEXT NOT NULL,
  last_content_hash TEXT,
  last_position INTEGER,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE
);
CREATE TABLE service_pco_links (
  id INTEGER PRIMARY KEY,
  service_id INTEGER NOT NULL,
  pco_service_type_id TEXT NOT NULL,
  pco_service_type_name TEXT,
  pco_plan_id TEXT NOT NULL,
  pco_plan_title TEXT,
  last_synced_at TEXT,
  last_sync_status TEXT,
  last_sync_error TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE
);
CREATE TABLE service_shares (
  id INTEGER PRIMARY KEY,
  service_id INTEGER NOT NULL,
  share_uuid TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE
);
CREATE TABLE services (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  title TEXT,
  rite TEXT,
  text_order TEXT CHECK (text_order IS NULL OR json_valid(text_order)),
  text_disabled TEXT CHECK (text_disabled IS NULL OR json_valid(text_disabled)),
  season TEXT,
  service_date TEXT,
  observance_handle TEXT,
  lesson_overrides JSON CHECK (lesson_overrides IS NULL OR json_valid(lesson_overrides)),
  offertory_sentence_id INTEGER,
  proper_overrides JSON CHECK (proper_overrides IS NULL OR json_valid(proper_overrides)),
  service_option_values JSON CHECK (service_option_values IS NULL OR json_valid(service_option_values)) DEFAULT '{}',
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE subcycles (
  id INTEGER PRIMARY KEY,
  handle TEXT,
  epoch INTEGER,
  order_value INTEGER,
  full_cycle INTEGER
);
CREATE TABLE texts (
  id INTEGER PRIMARY KEY,
  type TEXT,
  filter_type TEXT,
  filter_content TEXT,
  text TEXT,
  title TEXT,
  default_order INTEGER,
  detailed_title TEXT,
  reading INTEGER,
  option_group TEXT,
  optional INTEGER,
  book TEXT,
  book_name TEXT,
  reference_long TEXT,
  reference_short TEXT,
  note TEXT,
  subcycles JSON CHECK (subcycles IS NULL OR json_valid(subcycles))
);
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  email TEXT NOT NULL,
  password_hash TEXT,
  default_rite TEXT NOT NULL DEFAULT 'Renewed Ancient Text',
  default_bible_translation TEXT NOT NULL DEFAULT 'ESV',
  default_service_time TEXT NOT NULL DEFAULT '10:00',
  greeting_response_form TEXT NOT NULL DEFAULT 'with_your_spirit',
  deleted_at TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  last_login_at TEXT,
  last_accessed_at TEXT,
  feature_flags TEXT CHECK (feature_flags IS NULL OR json_valid(feature_flags))
);
CREATE INDEX idx_fragments_date_rule ON fragments(date_rule);
CREATE INDEX idx_holidays_handle ON holidays(handle);
CREATE INDEX idx_holidays_priority ON holidays(priority);
CREATE UNIQUE INDEX idx_pages_slug ON pages(slug);
CREATE INDEX idx_pco_batch_sync_jobs_status ON pco_batch_sync_jobs(status);
CREATE INDEX idx_pco_batch_sync_jobs_user_id ON pco_batch_sync_jobs(user_id);
CREATE INDEX idx_service_custom_elements_service_id ON service_custom_elements(service_id);
CREATE INDEX idx_service_custom_elements_user_id ON service_custom_elements(user_id);
CREATE INDEX idx_service_custom_templates_updated_at ON service_custom_templates(updated_at);
CREATE INDEX idx_service_custom_templates_user_id ON service_custom_templates(user_id);
CREATE UNIQUE INDEX idx_service_pco_item_links_service_pco_item ON service_pco_item_links(service_id, pco_item_id);
CREATE UNIQUE INDEX idx_service_pco_item_links_service_token ON service_pco_item_links(service_id, ordinarium_token);
CREATE UNIQUE INDEX idx_service_pco_links_service_id ON service_pco_links(service_id);
CREATE UNIQUE INDEX idx_service_shares_service_id ON service_shares(service_id);
CREATE UNIQUE INDEX idx_service_shares_uuid ON service_shares(share_uuid);
CREATE INDEX idx_services_rite ON services(rite);
CREATE INDEX idx_services_season ON services(season);
CREATE INDEX idx_services_service_date ON services(service_date);
CREATE INDEX idx_services_user_id ON services(user_id);
CREATE INDEX idx_services_user_id_service_date ON services(user_id, service_date);
CREATE INDEX idx_subcycles_handle ON subcycles(handle);
CREATE INDEX idx_subcycles_order_value ON subcycles(order_value);
CREATE INDEX idx_texts_filter_content on texts(filter_content);
CREATE INDEX idx_texts_filter_type on texts(filter_type);
CREATE INDEX idx_texts_lookup
  ON texts(type, filter_type, filter_content, default_order);
CREATE INDEX idx_texts_type on texts(type);
CREATE UNIQUE INDEX idx_users_email ON users(email);
PRAGMA foreign_keys = ON;
