CREATE TABLE "texts" ("id" INTEGER PRIMARY KEY, "data" JSON, type TEXT
generated always as (json_extract(data, "$.type")) virtual, filter_type TEXT
generated always as (json_extract(data, "$.filter.type")) virtual, filter_content TEXT
generated always as (json_extract(data, "$.filter.content")) virtual, text TEXT
generated always as (json_extract(data, "$.text")) virtual, title TEXT
generated always as (json_extract(data, '$.title')) virtual, default_order INTEGER
generated always as (json_extract(data, "$.default_order")) virtual);
INSERT INTO "texts" VALUES(1, '{"type": "proper_preface", "filter": {"type": "season", "content": "Christmastide"}, "text": "Because you gave Jesus Christ, your only Son, to be born for us; who, by the Holy Spirit and the Virgin Mary his mother, was made truly man, yet without the stain of sin, that we might be cleansed from sin and given the right to become your children."}');
INSERT INTO "texts" VALUES(2, '{"type": "proper_preface", "filter": {"type": "day", "content": "The Lord’s Day"}, "text": "Through Jesus Christ our Lord, who on the first day of the week overcame death and the grave, and by his glorious resurrection opened to us the way of everlasting life."}');
INSERT INTO "texts" VALUES(3, '{"type": "proper_preface", "filter": {"type": "other", "content": "At Any Time"}, "text": "Through Jesus Christ our Lord; for he is your living Word from before time and for all ages; by him you created all things, and by him you make all things new."}');
INSERT INTO "texts" VALUES(4, '{"type": "proper_preface", "filter": {"type": "other", "content": "At Any Time"}, "text": "For you are the source of light and life; you made us in your image, and called us to new life in Jesus Christ our Lord."}');
INSERT INTO "texts" VALUES(5, '{"type": "proper_preface", "filter": {"type": "season", "content": "Advent"}, "text": "Because you sent your beloved Son to redeem us from sin and death, and to make us heirs in him of everlasting life; that when he shall come again in power and great glory to judge the world, we may without shame or fear rejoice to behold his appearing."}');
INSERT INTO "texts" VALUES(6, '{"type": "proper_preface", "filter": {"type": "season", "content": "Epiphany"}, "text": "Through Jesus Christ our Lord, who took on our mortal flesh to reveal his glory; that he might bring us out of darkness and into his own glorious light."}');
INSERT INTO "texts" VALUES(7, '{"type": "proper_preface", "filter": {"type": "season", "content": "Presentation, Annunciation, and Transfiguration"}, "text": "Because in the mystery of the Word made flesh, you have caused a new light to shine in our hearts, to give the knowledge of your glory in the face of your Son Jesus Christ our Lord."}');
INSERT INTO "texts" VALUES(8, '{"type": "proper_preface", "filter": {"type": "season", "content": "Lent"}, "text": "You bid your faithful people cleanse their hearts, and prepare with joy for the Paschal feast; that, fervent in prayer and in works of mercy, and renewed by your Word and Sacraments, they may come to the fullness of grace which you have prepared for those who love you."}');
INSERT INTO "texts" VALUES(9, '{"type": "proper_preface", "filter": {"type": "season", "content": "Holy Week"}, "text": "Through Jesus Christ our Lord. For our sins he was lifted high upon the Cross, that he might draw the whole world to himself; and by his suffering and death he became the author of eternal salvation for all who put their trust in him."}');
INSERT INTO "texts" VALUES(10, '{"type": "proper_preface", "filter": {"type": "season", "content": "Maundy Thursday"}, "text": "Through Jesus Christ our Lord. Having loved his own who were in the world, he loved them to the end; and on the night before he suffered, he instituted these holy mysteries; that we, receiving the benefits of his passion and resurrection, might be made partakers of his divine nature."}');
INSERT INTO "texts" VALUES(11, '{"type": "proper_preface", "filter": {"type": "season", "content": "Easter"}, "text": "But chiefly are we bound to praise you for the glorious resurrection of your Son Jesus Christ our Lord; for he is the true Paschal Lamb, who was offered for us, and has taken away the sin of the world; who by his death has destroyed death, and by his rising to life again has won for us everlasting life."}');
INSERT INTO "texts" VALUES(12, '{"type": "proper_preface", "filter": {"type": "season", "content": "Ascension"}, "text": "Through your dearly beloved Son Jesus Christ our Lord, who after his most glorious resurrection appeared to his Apostles, and in their sight ascended into heaven to prepare a place for us; that where he is, there we might also ascend, and reign with him in glory."}');
INSERT INTO "texts" VALUES(13, '{"type": "proper_preface", "filter": {"type": "season", "content": "Pentecost"}, "text": "Through Jesus Christ our Lord; according to whose most true promise, the Holy Spirit came down from heaven, lighting upon the disciples, to teach them and to lead them into all truth, giving them boldness and fervent zeal constantly to preach the Gospel to all nations; by which we have been brought out of darkness and error into the clear light and true knowledge of you, and of your Son Jesus Christ."}');
INSERT INTO "texts" VALUES(14, '{"type": "proper_preface", "filter": {"type": "season", "content": "Trinity Sunday"}, "text": "Who, with your co-eternal Son and Holy Spirit, are one God, one Lord, in Trinity of Persons and in Unity of Substance. For that which we believe of your glory, O Father, we believe the same of your Son, and of the Holy Spirit, without any difference or inequality."}');
INSERT INTO "texts" VALUES(15, '{"type": "proper_preface", "filter": {"type": "season", "content": "All Saints’"}, "text": "For in the multitude of your saints, you have surrounded us with so great a cloud of witnesses that we, rejoicing in their fellowship, may run with patience the race that is set before us, and, together with them, may receive the unfading crown of glory."}');
INSERT INTO "texts" VALUES(16, '{"type": "proper_preface", "filter": {"type": "season", "content": "Christ the King"}, "text": "Through your only begotten Son Jesus Christ, the King of kings and Lord of lords; for you have seated him at your right hand in glory, and put all things in subjection under his feet, that he may present them to you, O Father, perfectly restored in beauty, truth, and love."}');
INSERT INTO "texts" VALUES(17, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Apostles and Ordinations"}, "text": "Through the great shepherd of your flock, Jesus Christ our Lord, who after his resurrection sent forth his apostles to preach the Gospel and to teach all nations, and promised to be with them always, even to the end of the ages."}');
INSERT INTO "texts" VALUES(18, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Dedication of a Church"}, "text": "Through Jesus Christ our great High Priest, in whom we are built up as living stones of a holy temple, that we might offer before you a sacrifice of praise and thanksgiving which is holy and pleasing in your sight."}');
INSERT INTO "texts" VALUES(19, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Baptism"}, "text": "Because in Jesus Christ our Lord, you have received us as your sons and daughters, made us citizens of your kingdom, and given us the Holy Spirit to guide us into all truth."}');
INSERT INTO "texts" VALUES(20, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Holy Matrimony"}, "text": "Because in the love of wife and husband, you have given us an image of the heavenly Jerusalem, adorned as a bride for her bridegroom, your Son Jesus Christ our Lord; who loves her and gave himself for her, that he might make the whole creation new."}');
INSERT INTO "texts" VALUES(21, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Burial or Commemoration of the Faithful Departed"}, "text": "Through Jesus Christ our Lord, who rose victorious from the dead and comforts us with the blessed hope of everlasting life. For to your faithful people, O Lord, life is changed, not ended; and when our mortal body lies in death, there is prepared for us a dwelling place eternal in the heavens."}');
INSERT INTO "texts" VALUES(22, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Penitential Occasions"}, "text": "Through Jesus Christ our Lord, who was tempted in every way as we are, yet did not sin. By his grace we are able to triumph over every evil, and to live no longer for ourselves alone, but for him who died for us and rose again."}');
INSERT INTO "texts" VALUES(23, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Rogation Days or Thanksgiving Day"}, "text": "Because the wonders of your Creation reflect your goodness and beauty; and your gifts of sun and rain, seed-time and harvest, manifest your constant love and care for all that you have made."}');
INSERT INTO "texts" VALUES(24, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Canada Day or Independence Day"}, "text": "Because you have made us in your image, that we might serve you on earth in freedom, justice, and peace; and have given us the hope of our eternal citizenship with you in your heavenly kingdom."}');
INSERT INTO "texts" VALUES(25, '{"type": "proper_preface", "filter": {"type": "occasion", "content": "Remembrance Day or Memorial Day"}, "text": "For by the sacrifice of your Son on the Cross, all who turn to him in the tribulation of war will find their peace with him in paradise."}');
INSERT INTO "texts" VALUES(26, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of a Martyr"}, "text": "For the witness of your martyrs, who took up their cross and followed you even unto death, and revealed your power made perfect in human weakness."}');
INSERT INTO "texts" VALUES(27, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of a Missionary or Evangelist"}, "text": "For the gifts of your Holy Spirit poured out upon prophets and evangelists, to proclaim the Gospel to the ends of the earth, and to bring all peoples under the reign of Jesus Christ our Lord."}');
INSERT INTO "texts" VALUES(28, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of a Pastor"}, "text": "Through Jesus Christ, the great shepherd of the sheep; in him you call faithful pastors and anoint them with your Holy Spirit, to feed your flock by Word and Sacrament, and to lead them in the way of everlasting life."}');
INSERT INTO "texts" VALUES(29, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of a Teacher of the Faith"}, "text": "For you have imparted gifts of wisdom and knowledge to those who teach the Gospel in word and deed, to build up the body of Christ, until we all attain to the unity of the faith and of the knowledge of the Son of God."}');
INSERT INTO "texts" VALUES(30, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of a Monastic or Religious"}, "text": "For calling to the consecrated life those who leave everything for the sake of your kingdom, and who show forth in this world an anticipation of the abundant life you promise in the age to come."}');
INSERT INTO "texts" VALUES(31, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of an Ecumenist"}, "text": "Through your Son Jesus Christ our Lord; in him you bring us to the knowledge of your truth, and unite us by the bond of one Faith and one Baptism, that we might love one another and manifest your love to the world."}');
INSERT INTO "texts" VALUES(32, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of a Renewer of Society"}, "text": "For you never turn away from us, and continually send among us those who seek justice, defend the oppressed, feed the poor, and bind up the brokenhearted."}');
INSERT INTO "texts" VALUES(33, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of a Reformer of the Church"}, "text": "For you, the master builder, never abandon your Church, which you have built of living stones; you call your faithful servants to restore its ancient walls and reunite its broken ramparts, that it may be a holy temple of your presence."}');
INSERT INTO "texts" VALUES(34, '{"type": "proper_preface", "filter": {"type": "common", "content": "Common of any Commemoration"}, "text": "For the grace and virtue manifest in [N. and all] your saints, who have been the chosen vessels of your love, and the lights of the world in their generations."}');
INSERT INTO "texts" VALUES(35, '{"type": "acclamation", "filter": {"type": "other", "content": "At Any Time"}, "text": "*&nbsp;* Blessed be God: the Father, the Son, and the Holy Spirit.  
*People* **And blessed be his kingdom, now and for ever. Amen.**"}');
INSERT INTO "texts" VALUES(36, '{"type": "acclamation", "filter": {"type": "season", "content": "Advent"}, "text": "*&nbsp;* Surely the Lord is coming soon.  
*People* **Amen. Come Lord Jesus!**
###### Revelation 22:20"}');
INSERT INTO "texts" VALUES(37, '{"type": "acclamation", "filter": {"type": "season", "content": "Christmastide"}, "text": "*&nbsp;* For unto us a child is born,  
*People* **Unto us a son is given.**
###### Isaiah 9:6T"}');
INSERT INTO "texts" VALUES(38, '{"type": "acclamation", "filter": {"type": "season", "content": "Feast of the Presentation of Christ"}, "text": "*&nbsp;* For unto us a child is born,  
*People* **Unto us a son is given.**
###### Isaiah 9:6T"}');
INSERT INTO "texts" VALUES(39, '{"type": "acclamation", "filter": {"type": "season", "content": "Epiphanytide"}, "text": "*&nbsp;* I will make you as a light for the nations,  
*People* **That my salvation may reach to the end of the earth.**
###### Isaiah 49:6"}');
INSERT INTO "texts" VALUES(40, '{"type": "acclamation", "filter": {"type": "season", "content": "Lent"}, "text": "*&nbsp;* Bless the Lord who forgives all our sins.  
*People* **His mercy endures for ever.**"}');
INSERT INTO "texts" VALUES(41, '{"type": "acclamation", "filter": {"type": "occasion", "content": "Penitential Occasions"}, "text": "*&nbsp;* Bless the Lord who forgives all our sins.  
*People* **His mercy endures for ever.**"}');
INSERT INTO "texts" VALUES(42, '{"type": "acclamation", "filter": {"type": "season", "content": "Holy Week"}, "text": "*&nbsp;* Blessed be our God.  
*People* **Now and for ever. Amen.**"}');
INSERT INTO "texts" VALUES(43, '{"type": "acclamation", "filter": {"type": "season", "content": "Easter"}, "text": "*&nbsp;* Alleluia! Christ is risen!  
*People* **The Lord is risen indeed! Alleluia!**"}');
INSERT INTO "texts" VALUES(44, '{"type": "acclamation", "filter": {"type": "season", "content": "Pentecost"}, "text": "*&nbsp;* The Lord will pour out his Spirit upon all flesh,  
*People* **And your sons and daughters shall prophesy.**  
*&nbsp;* Your old men shall dream dreams,  
*People* **And your young men shall see visions.**  
*&nbsp;* You shall know that the Lord is in the midst of his people,  
*People* **That he is the Lord and there is none else.**  
*&nbsp;* And it shall come to pass  
*People* **That everyone who calls on the Name of the Lord shall be saved.**
###### Joel 2:27-28, 32T; Acts 2:17, 21T"}');
INSERT INTO "texts" VALUES(45, '{"type": "acclamation", "filter": {"type": "occasion", "content": "Occasions of Confirmation and Ordination"}, "text": "*&nbsp;* The Lord will pour out his Spirit upon all flesh,  
*People* **And your sons and daughters shall prophesy.**  
*&nbsp;* Your old men shall dream dreams,  
*People* **And your young men shall see visions.**  
*&nbsp;* You shall know that the Lord is in the midst of his people,  
*People* **That he is the Lord and there is none else.**  
*&nbsp;* And it shall come to pass  
*People* **That everyone who calls on the Name of the Lord shall be saved.**
###### Joel 2:27-28, 32T; Acts 2:17, 21T"}');
INSERT INTO "texts" VALUES(46, '{"type": "acclamation", "filter": {"type": "season", "content": "All Saints’ Day"}, "text": "*&nbsp;* Worthy is the Lord our God,  
*People* **To receive glory and honor and power.**
###### Revelation 4:11T"}');
INSERT INTO "texts" VALUES(47, '{"type": "acclamation", "filter": {"type": "occasion", "content": "Other Appropriate Occasions"}, "text": "*&nbsp;* Worthy is the Lord our God,  
*People* **To receive glory and honor and power.**
###### Revelation 4:11T"}');
INSERT INTO "texts" VALUES(48, '{"type": "offertory_sentence", "text": "Remember the words of the Lord Jesus, how he himself said, “It is more blessed to give than to receive.”
###### Acts 20:35"}');
INSERT INTO "texts" VALUES(49, '{"type": "offertory_sentence", "text": "Let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven.
###### Matthew 5:16"}');
INSERT INTO "texts" VALUES(50, '{"type": "offertory_sentence", "text": "Do not lay up for yourselves treasures on earth, where moth and rust destroy and where thieves break in and steal, but lay up for yourselves treasures in heaven, where neither moth nor rust destroys and where thieves do not break in and steal. For where your treasure is, there your heart will be also.
###### Matthew 6:19-21"}');
INSERT INTO "texts" VALUES(51, '{"type": "offertory_sentence", "text": "Not everyone who says to me, “Lord, Lord,” will enter the kingdom of heaven, but the one who does the will of my Father who is in heaven.
###### Matthew 7:21"}');
INSERT INTO "texts" VALUES(52, '{"type": "offertory_sentence", "text": "Whoever sows sparingly will also reap sparingly, and whoever sows bountifully will also reap bountifully. Each one must give as he has decided in his heart, not reluctantly or under compulsion, for God loves a cheerful giver.
###### 2 Corinthians 9:6-7"}');
INSERT INTO "texts" VALUES(53, '{"type": "offertory_sentence", "text": "As we have opportunity, let us do good to everyone, and especially to those who are of the household of faith.
###### Galatians 6:10"}');
INSERT INTO "texts" VALUES(54, '{"type": "offertory_sentence", "text": "For God is not unjust so as to overlook your work and the love that you have shown for his name in serving the saints, as you still do.
###### Hebrews 6:10"}');
INSERT INTO "texts" VALUES(55, '{"type": "offertory_sentence", "text": "Do not neglect to do good and to share what you have, for such sacrifices are pleasing to God.
###### Hebrews 13:16"}');
INSERT INTO "texts" VALUES(56, '{"type": "offertory_sentence", "text": "If anyone has the world’s goods and sees his brother in need, yet closes his heart against him, how does God’s love abide in him?
###### 1 John 3:17"}');
INSERT INTO "texts" VALUES(57, '{"type": "offertory_sentence", "text": "If you have many possessions, make your gift from them in proportion; if few, do not be afraid to give according to the little you have. So you will be laying up a good treasure for yourself against the day of necessity.
###### Tobit 4:8-9"}');
INSERT INTO "texts" VALUES(58, '{"type": "offertory_sentence", "text": "And the King will answer them, “Truly, I say to you, as you did it to one of the least of these my brothers, you did it to me.”
###### Matthew 25:40"}');
INSERT INTO "texts" VALUES(59, '{"type": "offertory_sentence", "text": "How then will they call on him in whom they have not believed? And how are they to believe in him of whom they have never heard? And how are they to hear without someone preaching? And how are they to preach unless they are sent?
###### Romans 10:14-15"}');
INSERT INTO "texts" VALUES(60, '{"type": "offertory_sentence", "text": "And Jesus said to them, “The harvest is plentiful, but the laborers are few. Therefore pray earnestly to the Lord of the harvest to send out laborers into his harvest.”
###### Luke 10:2"}');
INSERT INTO "texts" VALUES(61, '{"type": "offertory_sentence", "text": "They shall not appear before the LORD empty-handed. Every man shall give as he is able, according to the blessing of the LORD your God that he has given you.
###### Deuteronomy 16:16-17"}');
INSERT INTO "texts" VALUES(62, '{"type": "offertory_sentence", "text": "Offer unto God a sacrifice of thanksgiving, and pay your vows unto the Most High.
###### Psalm 50:14"}');
INSERT INTO "texts" VALUES(63, '{"type": "offertory_sentence", "text": "Ascribe unto the LORD the honor due unto his Name; bring offerings and come into his courts.
###### Psalm 96:8"}');
INSERT INTO "texts" VALUES(64, '{"type": "offertory_sentence", "text": "Walk in love, as Christ loved us and gave himself up for us, a fragrant offering and sacrifice to God.
###### Ephesians 5:2"}');
INSERT INTO "texts" VALUES(65, '{"type": "offertory_sentence", "text": "I appeal to you therefore, brothers and sisters, by the mercies of God, to present your bodies as a living sacrifice, holy and acceptable to God, which is your spiritual worship.
###### Romans 12:1"}');
INSERT INTO "texts" VALUES(66, '{"type": "offertory_sentence", "text": "For you know the grace of our Lord Jesus Christ, that though he was rich, yet for your sake he became poor, so that you by his poverty might become rich.
###### 2 Corinthians 8:9"}');
INSERT INTO "texts" VALUES(67, '{"type": "offertory_sentence", "text": "You are a chosen race, a royal priesthood, a holy nation, a people for his own possession, that you may proclaim the excellencies of him who called you out of darkness into his marvelous light.
###### 1 Peter 2:9"}');
INSERT INTO "texts" VALUES(68, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The People standing, the Celebrant says*\n\n{{ acclamation | markdown }}","title":"The Acclamation","default_order":10}');
INSERT INTO "texts" VALUES(69, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Celebrant prays (and the People may be invited to join)*\n\nAlmighty God, to you all hearts are open, all desires known, and from you no secrets are hid: Cleanse the thoughts of our hearts by the inspiration of your Holy Spirit, that we may perfectly love you, and worthily magnify your holy Name; through Christ our Lord. **Amen.**","title":"The Collect for Purity","default_order":20}');
INSERT INTO "texts" VALUES(70, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*Then follows the Summary of the Law, or The Decalogue (page 100).*\n\nHear what our Lord Jesus Christ says:  \nYou shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the first and great commandment. And the second is like it: You shall love your neighbor as yourself. On these two commandments depend all the Law and the Prophets.\n###### Matthew 22:37-40T","title":"The Summary of the Law","default_order":30}');
INSERT INTO "texts" VALUES(71, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Celebrant and People pray*\n\n-   Lord, have mercy upon us.  \n    **Christ, have mercy upon us.**  \n    Lord, have mercy upon us.\n-   Lord, have mercy.  \n    **Christ, have mercy.**  \n    Lord, have mercy.\n-   Kyrie eleison.  \n    **Christe eleison.**  \n    Kyrie eleison.\n\n*or this*","title":"The Kyrie","default_order":40}');
INSERT INTO "texts" VALUES(72, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"Holy God,  \nHoly and Mighty,  \nHoly Immortal One,  \n**Have mercy upon us.**","title":"The Trisagion","default_order":50}');
INSERT INTO "texts" VALUES(73, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Gloria or some other song of praise may be sung or said, all standing. It is appropriate to omit the song of praise during penitential seasons and days appointed for fasting.*\n\n    Glory to God in the highest,\n        and peace to his people on earth.\n    Lord God, heavenly King,\n    almighty God and Father, \n        we worship you, we give you thanks,\n        we praise you for your glory.\n    Lord Jesus Christ, only Son of the Father,\n    Lord God, Lamb of God,\n    you take away the sin of the world:\n        have mercy on us;\n    you are seated at the right hand of the Father:\n        receive our prayer.\n    For you alone are the Holy One,\n    you alone are the Lord,\n    you alone are the Most High,\n        Jesus Christ,\n        with the Holy Spirit,\n        in the glory of God the Father. Amen.","title":"The Gloria in Excelsis","default_order":60}');
INSERT INTO "texts" VALUES(74, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Celebrant says to the People*\n\n*&nbsp;* The Lord be with you.  \n*People* **And with your spirit.**  \n*Officiant* Let us pray.\n\n*The Celebrant prays the Collect.*\n\n{{ collect_of_the_day | markdown }}\n\n*People* **Amen.**","title":"The Collect of the Day","default_order":70}');
INSERT INTO "texts" VALUES(75, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*One or more Lessons, as appointed, are read, the Reader first saying*\n\n**A Reading from {{ lesson_1_reference }}.**\n\n*A citation giving chapter and verse may be added.*\n\n*After each Lesson the Reader may say*\n\n*&nbsp;* The Word of the Lord.  \n*People* **Thanks be to God.**\n\n*Or the Reader may say* **Here ends the Reading.**\n\n*Silence may follow.*","title":"The Lessons","default_order":80}');
INSERT INTO "texts" VALUES(76, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*A psalm, hymn, or anthem may follow each reading.*\n\n{{ psalm_reference }}","title":"The Lessons","default_order":90}');
INSERT INTO "texts" VALUES(77, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*One or more Lessons, as appointed, are read, the Reader first saying*\n\n**A Reading from {{ lesson_2_reference }}.**\n\n*A citation giving chapter and verse may be added.*\n\n*After each Lesson the Reader may say*\n\n*&nbsp;* The Word of the Lord.  \n*People* **Thanks be to God.**\n\n*Or the Reader may say* **Here ends the Reading.**\n\n*Silence may follow.*","title":"The Lessons","default_order":100}');
INSERT INTO "texts" VALUES(78, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*All standing, the Deacon or Priest reads the Gospel, first saying*\n\n*&nbsp;* The Holy Gospel of our Lord Jesus Christ according to {{ gospel_reference }}.  \n*People* **Glory to you, Lord Christ.**\n\n*After the Gospel, the Reader says*\n\n*&nbsp;* The Gospel of the Lord.  \n*People* **Praise to you, Lord Christ.**","title":"The Lessons","default_order":110}');
INSERT INTO "texts" VALUES(79, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":null,"title":"The Sermon","default_order":120}');
INSERT INTO "texts" VALUES(80, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*On Sundays, other Major Feast Days, and other times as appointed, all stand to recite the Nicene Creed, the Celebrant first saying*\n\nLet us confess our faith in the words of the Nicene Creed:\n\n*Celebrant and People*\n\n    We believe in one God,\n        the Father, the Almighty,\n        maker of heaven and earth,\n        of all that is, visible and invisible.\n\n    We believe in one Lord, Jesus Christ,\n        the only-begotten Son of God,\n        eternally begotten of the Father,\n        God from God, Light from Light,\n        true God from true God,\n        begotten, not made,\n        of one Being with the Father;\n        through him all things were made.\n        For us and for our salvation he came down from heaven,\n        was incarnate from the Holy Spirit and the Virgin Mary,\n        and was made man.\n        For our sake he was crucified under Pontius Pilate;\n        he suffered death and was buried.\n        On the third day he rose again in accordance with the Scriptures;\n        he ascended into heaven\n        and is seated at the right hand of the Father.\n        He will come again in glory to judge the living and the dead,\n        and his kingdom will have no end.\n\n    We believe in the Holy Spirit, the Lord, the giver of life,\n        who proceeds from the Father [and the Son],  \n        who with the Father and the Son is worshiped and glorified,\n        who has spoken through the prophets.\n        We believe in one holy catholic and apostolic Church.\n        We acknowledge one Baptism for the forgiveness of sins.\n        We look for the resurrection of the dead,\n        and the life of the world to come. Amen.","title":"The Nicene Creed","default_order":130}');
INSERT INTO "texts" VALUES(81, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Deacon or other person appointed says these prayers, or the Prayers of the People in the Anglican Standard Text. The reader pauses after each bidding, and the people may add petitions, either silently or aloud.*\n\nLet us pray for the Church and for the world, saying, “hear our prayer.”\n\nFor the peace of the whole world, and for the well-being and unity of the people of God.\n\n*Reader* Lord, in your mercy:  \n*People* **Hear our prayer.**\n\nFor N., our Archbishop, and N., our Bishop, and for all the clergy and people of our Diocese and Congregation.\n\n*Reader* Lord, in your mercy:  \n*People* **Hear our prayer.**\n\nFor all those who proclaim the Gospel at home and abroad; and for all who teach and disciple others.\n\n*Reader* Lord, in your mercy:  \n*People* **Hear our prayer.**\n\nFor our brothers and sisters in Christ who are persecuted for their faith.\n\n*Reader* Lord, in your mercy:  \n*People* **Hear our prayer.**\n\nFor our nation, for those in authority, and for all in public service [especially _____________].\n\n*Reader* Lord, in your mercy:  \n*People* **Hear our prayer.**\n\nFor all those who are in trouble, sorrow, need, sickness, or any other adversity [especially _____________].\n\n*Reader* Lord, in your mercy:  \n*People* **Hear our prayer.**\n\nFor all those who have departed this life in the certain hope of the resurrection, [especially ______,] in thanksgiving let us pray.\n\n*Reader* Lord, in your mercy:  \n*People* **Hear our prayer.**\n\n*Additional petitions may be added. Thanksgivings may also be invited.*\n\n*The Celebrant concludes with this or some other appropriate Collect.*\n\nHeavenly Father, grant these our prayers for the sake of Jesus Christ, our only Mediator and Advocate, who lives and reigns with you in the unity of the Holy Spirit, one God, now and for ever. **Amen.**\n\n*The Celebrant may then say the Exhortation.*","title":"The Prayers of the People","default_order":140}');
INSERT INTO "texts" VALUES(82, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Deacon or other person appointed says the following*\n\nLet us humbly confess our sins to Almighty God.\n\n*Silence*\n\n*The Deacon and People kneel as able and pray*\n\n    Most merciful God,\n        we confess that we have sinned against you\n        in thought, word, and deed,\n        by what we have done, and by what we have left undone.\n    We have not loved you with our whole heart;\n        we have not loved our neighbors as ourselves.\n    We are truly sorry and we humbly repent.\n    For the sake of your Son Jesus Christ,\n        have mercy on us and forgive us;\n        that we may delight in your will, and walk in your ways,\n        to the glory of your Name. Amen.\n\n*The Bishop or Priest stands and says*\n\nAlmighty God, our heavenly Father, who in his great mercy has promised forgiveness of sins to all those who sincerely repent and with true faith turn to him, have mercy upon you, pardon and deliver you from all your sins, confirm and strengthen you in all goodness, and bring you to everlasting life; through Jesus Christ our Lord. **Amen.**","title":"The Confession and Absolution of Sin","default_order":150}');
INSERT INTO "texts" VALUES(83, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Celebrant may then say one or more of the following sentences, first saying*\n\nHear the Word of God to all who truly turn to him.\n\nCome to me, all who labor and are heavy laden, and I will give you rest.\n###### Matthew 11:28\n\nGod so loved the world, that he gave his only-begotten Son, that whoever believes in him should not perish but have eternal life.\n###### John 3:16T\n\nThe saying is trustworthy and deserving of full acceptance, that Christ Jesus came into the world to save sinners.\t\n###### 1 Timothy 1:15\n\nIf anyone sins, we have an advocate with the Father, Jesus Christ the righteous. He is the propitiation for our sins, and not for ours only, but also for the sins of the whole world.\n###### 1 John 2:1-2T","title":"The Comfortable Words","default_order":160}');
INSERT INTO "texts" VALUES(84, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*Celebrant* The Peace of the Lord be always with you.  \n*People* **And with your spirit.**\n\n*Then the Ministers and People may greet one another in the Name of the Lord.*","title":"The Peace","default_order":170}');
INSERT INTO "texts" VALUES(85, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Celebrant may begin the Offertory with one of the provided sentences of Scripture.*\n\n{{ offertory_sentence | markdown }}\n\n*During the Offertory a hymn, psalm, or anthem may be sung. The Deacon or Priest prepares the Holy Table for the celebration. Representatives of the Congregation may bring the People’s offerings of bread and wine, and money or other gifts, to the Deacon or Priest.*\n\n*The People stand while the offerings are presented. The following may be said.*\n\n*Celebrant* <span class=\"trailing-indent\">Yours, O LORD, is the greatness, and the power, and the glory, and the victory, and the majesty: for everything in heaven and on earth is yours; yours is the kingdom, O LORD, and you are exalted as Head above all. All things come from you, O LORD,</span>  \n*People* **And of your own have we given you.**\n###### 1 Chronicles 29:11, 14T","title":"The Offertory","default_order":180}');
INSERT INTO "texts" VALUES(86, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The People remain standing. The Celebrant faces them and sings or says*\n\n*&nbsp;* The Lord be with you.  \n*People* **And with your spirit.**  \n*Celebrant* Lift up your hearts.  \n*People* **We lift them up to the Lord.**  \n*Celebrant* Let us give thanks to the Lord our God.  \n*People* **It is right to give him thanks and praise.**\n\n*The Celebrant continues*\n\nIt is right, our duty and our joy, always and everywhere to give thanks to you, Father Almighty, Creator of heaven and earth.\n\n{{ proper_preface | markdown }}\n\nTherefore we praise you, joining our voices with Angels and Archangels and with all the company of heaven, who for ever sing this hymn to proclaim the glory of your Name:","title":"The Sursum Corda","default_order":190}');
INSERT INTO "texts" VALUES(87, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*Celebrant and People*\n\n    Holy, Holy, Holy, Lord God of power and might, heaven and earth are full of your glory.\n        Hosanna in the highest.\n    Blessed is he who comes in the Name of the Lord.\n        Hosanna in the highest.","title":"The Sanctus","default_order":200}');
INSERT INTO "texts" VALUES(88, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The People stand or kneel. The Celebrant continues*\n\nHoly and gracious Father: In your infinite love you made us for yourself; and when we had sinned against you and become subject to evil and death, you, in your mercy, sent your only Son Jesus Christ into the world for our salvation. By the Holy Spirit and the Virgin Mary he became flesh and dwelt among us. In obedience to your will, he stretched out his arms upon the Cross and offered himself once for all, that by his suffering and death we might be saved. By his resurrection he broke the bonds of death, trampling Hell and Satan under his feet. As our great high priest, he ascended to your right hand in glory, that we might come with confidence before the throne of grace.\n\n*At the following words concerning the bread, the Celebrant is to hold it, or lay a hand upon it, and here\\* may break the bread; and at the words concerning the cup, to hold or place a hand upon the cup and any other vessel containing the wine to be consecrated.*\n\nOn the night that he was betrayed, our Lord Jesus Christ took bread; and when he had given thanks, he broke it,\\* and gave it to his disciples, saying, “Take, eat; this is my Body, which is given for you: Do this in remembrance of me.”\n\nLikewise, after supper, Jesus took the cup, and when he had given thanks, he gave it to them, saying, “Drink this, all of you; for this is my Blood of the New Covenant, which is shed for you, and for many, for the forgiveness of sins: Whenever you drink it, do this in remembrance of me.”\n\nTherefore we proclaim the mystery of faith:\n\n*Celebrant and People*\n\n    Christ has died.\n    Christ is risen.\n    Christ will come again.\n\nWe celebrate the memorial of our redemption, O Father, in this sacrifice of praise and thanksgiving, and we offer you these gifts.\n\nSanctify them by your Word and Holy Spirit to be for your people the Body and Blood of your Son Jesus Christ. Sanctify us also, that we may worthily receive this holy Sacrament, and be made one body with him, that he may dwell in us and we in him. In the fullness of time, put all things in subjection under your Christ, and bring us with all your saints into the joy of your heavenly kingdom, where we shall see our Lord face to face.\n\nAll this we ask through your Son Jesus Christ: By him, and with him, and in him, in the unity of the Holy Spirit, all honor and glory is yours, Almighty Father, now and for ever. **Amen.**","title":"The Prayer of Consecration","default_order":210}');
INSERT INTO "texts" VALUES(89, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Celebrant then says*\n\nAnd now as our Savior Christ has taught us, we are bold to pray:\n\n*Celebrant and People together pray*\n\n- ```Our Father, who art in heaven,\n        hallowed be thy Name,\n        thy kingdom come,\n        thy will be done,\n        on earth as it is in heaven.\n    Give us this day our daily bread.\n    And forgive us our trespasses,\n        as we forgive those\n        who trespass against us.\n    And lead us not into temptation,\n        but deliver us from evil.\n    For thine is the kingdom,\n        and the power, and the glory,\n        for ever and ever. Amen.```\n- ```Our Father in heaven,\n        hallowed be your Name,\n        your kingdom come,\n        your will be done,\n        on earth as it is in heaven.\n    Give us today our daily bread.\n    And forgive us our sins\n        as we forgive those\n        who sin against us.\n    Save us from the time of trial,\n        and deliver us from evil.\n    For the kingdom, the power,\n        and the glory are yours,\n        now and for ever. Amen.```","title":"The Lord’s Prayer","default_order":220}');
INSERT INTO "texts" VALUES(90, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*If the consecrated Bread was not broken earlier, the Celebrant breaks it now.*\n\n*A period of silence is kept.*\n\n*Then may be sung or said*\n\n*Celebrant* [Alleluia.] Christ our Passover is sacrificed for us.  \n*People* **Therefore let us keep the feast. [Alleluia.]**\n\n*or this*\n\n*Celebrant* [Alleluia.] Christ our Passover Lamb has been sacrificed, once for all upon the Cross.  \n*People* **Therefore let us keep the feast. [Alleluia.]**\n\n*In Lent, Alleluia is omitted, and may be omitted at other times except during Easter Season.*","title":"The Fraction","default_order":230}');
INSERT INTO "texts" VALUES(91, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*Celebrant and People together may say*\n\n    We do not presume to come to this your table, O merciful Lord,\n        trusting in our own righteousness,\n        but in your abundant and great mercies.\n    We are not worthy so much as to gather up\n        the crumbs under your table;\n        but you are the same Lord\n        whose character is always to have mercy.\n    Grant us, therefore, gracious Lord,\n        so to eat the flesh of your dear Son Jesus Christ,\n        and to drink his blood,\n        that our sinful bodies may be made clean by his body,\n        and our souls washed through his most precious blood,\n        and that we may evermore dwell in him, and he in us. Amen.","title":"The Prayer of Humble Access","default_order":240}');
INSERT INTO "texts" VALUES(92, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The following or some other suitable anthem may be sung or said here*\n\nLamb of God, you take away the sin of the world;  \n    **have mercy on us.**  \nLamb of God, you take away the sin of the world;  \n    **have mercy on us.**  \nLamb of God, you take away the sin of the world;  \n    **grant us your peace.**","title":"The Agnus Dei","default_order":250}');
INSERT INTO "texts" VALUES(93, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*Facing the People, the Celebrant may say the following invitation*\n\nThe gifts of God for the people of God. [Take them in remembrance that Christ died for you and feed on him in your hearts by faith, with thanksgiving.]\n\n*or this*\n\nBehold the Lamb of God, behold him who takes away the sins of the world. Blessed are those who are invited to the marriage supper of the Lamb.\n###### John 1:29T, Revelation 19:9\n\n*The Ministers receive the Sacrament in both kinds, and then immediately deliver it to the People.*\n\n*The Bread and Cup are given to the communicants with these words*\n\nThe Body of our Lord Jesus Christ, [which was given for you, preserve your body and soul to everlasting life. Take and eat this in remembrance that Christ died for you, and feed on him in your heart by faith, with thanksgiving.]\n\nThe Blood of our Lord Jesus Christ, [which was shed for you, preserve your body and soul to everlasting life. Drink this in remembrance that Christ’s Blood was shed for you, and be thankful.]\n\n*During the ministration of Communion, hymns, psalms, or anthems may be sung.*\n\n*The Celebrant may offer a sentence of Scripture at the conclusion of the Communion.*","title":"The Ministration of Communion","default_order":260}');
INSERT INTO "texts" VALUES(94, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*After Communion, the Celebrant says*\n\nLet us pray.\n\n*Celebrant and People together say the following, or the Post Communion Prayer in the Anglican Standard Text*\n\n    Heavenly Father,\n    We thank you for feeding us with the spiritual food\n        of the most precious Body and Blood\n        of your Son our Savior Jesus Christ;\n        and for assuring us in these holy mysteries\n        that we are living members of the body of your Son,\n        and heirs of your eternal kingdom.\n    And now, Father, send us out to do the work you have given us to do,\n        to love and serve you as faithful witnesses of Christ our Lord.\n    To him, to you, and to the Holy Spirit,\n        be honor and glory, now and for ever. Amen.","title":"The Post Communion Prayer","default_order":270}');
INSERT INTO "texts" VALUES(95, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Bishop when present, or the Priest, gives this or an alternate blessing*\n\nThe peace of God, which passes all understanding, keep your hearts and minds in the knowledge and love of God, and of his Son Jesus Christ our Lord; and the blessing of God Almighty, the Father, the Son, and the Holy Spirit, be among you, and remain with you always. **Amen.**\n\n*A hymn, psalm, or anthem may be sung after the Blessing (or following the Dismissal).*","title":"The Blessing","default_order":280}');
INSERT INTO "texts" VALUES(96, '{"type":"ordinarium","filter":{"type":"rite","content":"Renewed Ancient Text"},"text":"*The Deacon, or the Priest, may dismiss the People with these words*\n\n*&nbsp;* Let us go forth in the Name of Christ.  \n*People* **Thanks be to God.**\n\n*or this*\n\n*Deacon* Go in peace to love and serve the Lord.  \n*People* **Thanks be to God.**\n\n*or this*\n\n*Deacon* Let us go forth into the world, rejoicing in the power of the Holy Spirit.  \n*People* **Thanks be to God.**\n\n*or this*\n\n*Deacon* Let us bless the Lord.  \n*People* **Thanks be to God.**\n\n*From the Easter Vigil through the Day of Pentecost, “Alleluia, alleluia” is added to any of the dismissals. It may be added at other times, except during Lent and on other penitential occasions.*\n\n*The People respond*\n\n**Thanks be to God. Alleluia, alleluia.**","title":"The Dismissal","default_order":290}');
CREATE INDEX idx_texts_type on texts(type);
CREATE INDEX idx_texts_filter_type on texts(filter_type);
CREATE INDEX idx_texts_filter_content on texts(filter_content);
