#!/usr/bin/env python3
import argparse
import sqlite3
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from ordinarium import create_app
from ordinarium.db import init_db


REFERENCE_TABLES = ("holidays", "fragments", "subcycles", "pages", "texts")
EXCLUDED_TABLES = {
    "id_sequences",
    "password_reset_requests",
    "pco_batch_sync_rows",
    "pco_plan_operations",
    "pco_rate_limit_windows",
    "pco_service_sync_leases",
    "schema_migrations",
    "user_text_overrides",
}
EXCLUDED_OBJECT_PREFIXES = ("sync_id_sequence_",)
EXCLUDED_INDEXES = {
    "idx_service_custom_elements_stable_token",
    "idx_services_creation_token",
}
POST_BASELINE_COLUMNS = {
    "pco_batch_sync_jobs": (
        "  claim_token TEXT,\n",
        "  claim_expires_at INTEGER,\n",
        "  delivery_attempts INTEGER NOT NULL DEFAULT 0,\n",
    ),
    "pco_connections": (
        "  version INTEGER NOT NULL DEFAULT 1,\n",
        "  refresh_claim_token TEXT,\n",
        "  refresh_claim_expires_at INTEGER,\n",
    ),
    "service_custom_elements": ("  stable_token TEXT,\n",),
    "services": ("  creation_token TEXT,\n",),
}


def build_fresh_database(path):
    app = create_app()
    app.config.update(DATABASE=str(path), TESTING=True)
    with app.app_context():
        init_db()


def schema_sql(connection):
    rows = connection.execute(
        """
        select type, name, sql
        from sqlite_master
        where sql is not null
          and name not like 'sqlite_%'
        order by case type when 'table' then 0 else 1 end, name
        """
    ).fetchall()
    statements = []
    for object_type, name, sql in rows:
        if name.startswith(EXCLUDED_OBJECT_PREFIXES):
            continue
        if name in EXCLUDED_INDEXES:
            continue
        if object_type == "table" and name in EXCLUDED_TABLES:
            continue
        if object_type == "index" and _index_targets_excluded_table(connection, name):
            continue
        for column_sql in POST_BASELINE_COLUMNS.get(name, ()):
            sql = sql.replace(column_sql, "")
        statements.append(f"{sql.rstrip(';')};")
    return _document(
        "Schema generated from a freshly initialized main SQLite database.",
        ["PRAGMA foreign_keys = OFF;", *statements, "PRAGMA foreign_keys = ON;"],
    )


def reference_data_sql(connection):
    statements = ["PRAGMA foreign_keys = OFF;"]
    for table in REFERENCE_TABLES:
        columns = [
            row[1] for row in connection.execute(f'PRAGMA table_info("{table}")')
        ]
        column_sql = ", ".join(_quote_identifier(column) for column in columns)
        order_column = "id" if "id" in columns else columns[0]
        rows = connection.execute(
            f'SELECT * FROM "{table}" ORDER BY "{order_column}"'
        ).fetchall()
        for row in rows:
            values_sql = ", ".join(_sql_literal(value) for value in row)
            statements.append(
                f'INSERT INTO "{table}" ({column_sql}) VALUES ({values_sql});'
            )
    statements.append("PRAGMA foreign_keys = ON;")
    return _document(
        "Reference data generated from main; user and service rows are excluded.",
        statements,
    )


def generate(output_dir):
    output_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as directory:
        database_path = Path(directory) / "fresh-main.sqlite3"
        build_fresh_database(database_path)
        connection = sqlite3.connect(database_path)
        try:
            (output_dir / "0001_baseline.sql").write_text(
                schema_sql(connection), encoding="utf-8"
            )
            (output_dir / "0002_reference_data.sql").write_text(
                reference_data_sql(connection), encoding="utf-8"
            )
        finally:
            connection.close()


def _index_targets_excluded_table(connection, index_name):
    row = connection.execute(
        "select tbl_name from sqlite_master where type='index' and name=?",
        (index_name,),
    ).fetchone()
    return bool(row and row[0] in EXCLUDED_TABLES)


def _quote_identifier(value):
    return f'"{value.replace(chr(34), chr(34) * 2)}"'


def _sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bytes):
        return f"X'{value.hex()}'"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _document(description, statements):
    return "\n".join(
        [
            "-- Generated by scripts/cloudflare/generate_d1_baseline.py.",
            f"-- {description}",
            "",
            *statements,
            "",
        ]
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "migrations" / "d1",
    )
    args = parser.parse_args()
    generate(args.output_dir)


if __name__ == "__main__":
    main()
