#!/usr/bin/env python3
import argparse
import os
from pathlib import Path

from container_role_apps import create_documents_app
from document_rendering import render_docx_bytes, render_pdf_bytes


AUTH_TOKEN = "phase6-comparison-proof"
FIXTURE_CSS = """
@page { margin: 1in; }
body { color: #000; font-family: Georgia, serif; font-size: 11pt; }
#text h1 { font-size: 1.36em; font-weight: 200; text-align: center; text-transform: uppercase; }
#text h1 small, #text h2, #text h3, #text p em { color: #c62f7c; }
#text h2 { font-size: 1.1em; font-style: italic; text-align: center; }
#text h3 { font-size: 0.91em; font-weight: 400; letter-spacing: 0.1em; text-align: center; text-transform: uppercase; }
#text p { margin: 0.91em 0; break-inside: avoid; }
#text p > em:first-child:not(:last-child) { display: inline-block; margin-right: 0.5em; min-width: 4.5em; text-align: right; }
#text p > .trailing-indent { display: inline-block; width: calc(100% - 5em); vertical-align: top; }
#text .text-footer { color: #c62f7c; font-size: 0.8em; margin-top: 2em; text-align: center; }
"""


def representative_html():
    return f"""<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><style>{FIXTURE_CSS}</style></head>
<body><main id="text">
  <h1>Holy Eucharist<br><small>Renewed Ancient Text</small></h1>
  <h2>The Second Sunday after Christmas Day</h2>
  <section class="text-element"><h3>Opening Acclamation</h3>
    <p><em>Celebrant</em><span class="trailing-indent">Blessed be God: the Father, the Son, and the Holy Spirit.</span></p>
    <p><em>People</em><span class="trailing-indent"><strong>And blessed be his kingdom, now and for ever. Amen.</strong></span></p>
  </section>
  <section class="text-element"><h3>The Collect</h3>
    <p>Almighty God, you have poured upon us the new light of your incarnate Word.</p>
  </section>
  <p class="text-footer">Generated by Ordinarium</p>
</main></body></html>"""


def representative_docx_context():
    return {
        "title": "Holy Eucharist",
        "rite": "Renewed Ancient Text",
        "service_title": "The Second Sunday after Christmas Day",
        "service_date_display": "January 4, 2026",
        "generated_at_display": "January 4, 2026 at 9:00 AM",
        "ordinaries": [
            {
                "type": "ordinary",
                "title_inline_html": "Opening Acclamation",
                "body_html": (
                    "<p><em>Celebrant</em> Blessed be God: the Father, the Son, "
                    "and the Holy Spirit.</p><p><em>People</em> <strong>And blessed "
                    "be his kingdom, now and for ever. Amen.</strong></p>"
                ),
                "show_title": True,
            },
            {
                "type": "ordinary",
                "title_inline_html": "The Collect",
                "body_html": (
                    "<p>Almighty God, you have poured upon us the new light of "
                    "your incarnate Word.</p>"
                ),
                "show_title": True,
            },
        ],
    }


def render_direct(output_directory, prefix):
    (output_directory / f"{prefix}.pdf").write_bytes(
        render_pdf_bytes(representative_html(), base_url="/app/ordinarium")
    )
    (output_directory / f"{prefix}.docx").write_bytes(
        render_docx_bytes(representative_docx_context())
    )


def render_through_service(output_directory, prefix):
    os.environ["DOCUMENT_SERVICE_AUTH_TOKEN"] = AUTH_TOKEN
    app = create_documents_app()
    client = app.test_client()
    headers = {"X-Ordinarium-Document-Auth": AUTH_TOKEN}
    requests = {
        "pdf": {"format": "pdf", "html": representative_html()},
        "docx": {"format": "docx", "context": representative_docx_context()},
    }
    for extension, payload in requests.items():
        response = client.post("/render", json=payload, headers=headers)
        if response.status_code != 200:
            raise AssertionError(
                f"{extension} service render failed: "
                f"status={response.status_code} body={response.get_data(as_text=True)}"
            )
        (output_directory / f"{prefix}.{extension}").write_bytes(response.data)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("direct", "service"))
    parser.add_argument("output_directory", type=Path)
    parser.add_argument("prefix")
    args = parser.parse_args()
    args.output_directory.mkdir(parents=True, exist_ok=True)
    if args.mode == "direct":
        render_direct(args.output_directory, args.prefix)
    else:
        render_through_service(args.output_directory, args.prefix)


if __name__ == "__main__":
    main()
